{"uuid":"be7f0ada-0c8c-4d5b-939e-d87b5317dbae","historyId":"4446b8aea5449c8a8978754c0a82c780","status":"broken","statusDetails":{"message":"`cy.request()` failed trying to load:\n\nhttps://conexaoqa.herokuapp.com/api/auth\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo ENOENT conexaoqa.herokuapp.com\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: https://conexaoqa.herokuapp.com/api/auth\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer","trace":"CypressError: `cy.request()` failed trying to load:\n\nhttps://conexaoqa.herokuapp.com/api/auth\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo ENOENT conexaoqa.herokuapp.com\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: https://conexaoqa.herokuapp.com/api/auth\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n    at https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:158822:78\nFrom previous event:\n    at Context.request (https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:158819:15)\nFrom Your Spec Code:\n    at Context.eval (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\support\\e2e.js:1498:6)\n\nFrom Node.js Internals:\n  RequestError: Error: getaddrinfo ENOENT conexaoqa.herokuapp.com\n      at new RequestError (C:\\Users\\2160000778\\AppData\\Local\\Cypress\\Cache\\10.4.0\\Cypress\\resources\\app\\node_modules\\request-promise-core\\lib\\errors.js:14:15)\n      at Request.plumbing.callback (C:\\Users\\2160000778\\AppData\\Local\\Cypress\\Cache\\10.4.0\\Cypress\\resources\\app\\node_modules\\request-promise-core\\lib\\plumbing.js:87:29)\n      at Request.RP$callback [as _callback] (C:\\Users\\2160000778\\AppData\\Local\\Cypress\\Cache\\10.4.0\\Cypress\\resources\\app\\node_modules\\request-promise-core\\lib\\plumbing.js:46:31)\n      at self.callback (C:\\Users\\2160000778\\AppData\\Local\\Cypress\\Cache\\10.4.0\\Cypress\\resources\\app\\node_modules\\@cypress\\request\\request.js:183:22)\n      at Request.emit (node:events:526:28)\n      at Request.emit (node:domain:475:12)\n      at Request.onRequestError (C:\\Users\\2160000778\\AppData\\Local\\Cypress\\Cache\\10.4.0\\Cypress\\resources\\app\\node_modules\\@cypress\\request\\request.js:869:8)\n      at ClientRequest.emit (node:events:538:35)\n      at ClientRequest.emit (node:domain:475:12)\n      at TLSSocket.socketErrorListener (node:_http_client:442:9)\n      at TLSSocket.emit (node:events:526:28)\n      at TLSSocket.emit (node:domain:475:12)\n      at emitErrorNT (node:internal/streams/destroy:157:8)\n      at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n      at processTicksAndRejections (node:internal/process/task_queues:83:21)\n  "},"stage":"finished","steps":[{"status":"failed","statusDetails":{"message":"`cy.request()` failed trying to load:\n\nhttps://conexaoqa.herokuapp.com/api/auth\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo ENOENT conexaoqa.herokuapp.com\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: https://conexaoqa.herokuapp.com/api/auth\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer","trace":"CypressError: `cy.request()` failed trying to load:\n\nhttps://conexaoqa.herokuapp.com/api/auth\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo ENOENT conexaoqa.herokuapp.com\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: https://conexaoqa.herokuapp.com/api/auth\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n    at https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:158822:78\nFrom previous event:\n    at Context.request (https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:158819:15)\nFrom Your Spec Code:\n    at Context.eval (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\support\\e2e.js:1498:6)\n\nFrom Node.js Internals:\n  RequestError: Error: getaddrinfo ENOENT conexaoqa.herokuapp.com\n      at new RequestError (C:\\Users\\2160000778\\AppData\\Local\\Cypress\\Cache\\10.4.0\\Cypress\\resources\\app\\node_modules\\request-promise-core\\lib\\errors.js:14:15)\n      at Request.plumbing.callback (C:\\Users\\2160000778\\AppData\\Local\\Cypress\\Cache\\10.4.0\\Cypress\\resources\\app\\node_modules\\request-promise-core\\lib\\plumbing.js:87:29)\n      at Request.RP$callback [as _callback] (C:\\Users\\2160000778\\AppData\\Local\\Cypress\\Cache\\10.4.0\\Cypress\\resources\\app\\node_modules\\request-promise-core\\lib\\plumbing.js:46:31)\n      at self.callback (C:\\Users\\2160000778\\AppData\\Local\\Cypress\\Cache\\10.4.0\\Cypress\\resources\\app\\node_modules\\@cypress\\request\\request.js:183:22)\n      at Request.emit (node:events:526:28)\n      at Request.emit (node:domain:475:12)\n      at Request.onRequestError (C:\\Users\\2160000778\\AppData\\Local\\Cypress\\Cache\\10.4.0\\Cypress\\resources\\app\\node_modules\\@cypress\\request\\request.js:869:8)\n      at ClientRequest.emit (node:events:538:35)\n      at ClientRequest.emit (node:domain:475:12)\n      at TLSSocket.socketErrorListener (node:_http_client:442:9)\n      at TLSSocket.emit (node:events:526:28)\n      at TLSSocket.emit (node:domain:475:12)\n      at emitErrorNT (node:internal/streams/destroy:157:8)\n      at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n      at processTicksAndRejections (node:internal/process/task_queues:83:21)\n  "},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"failed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1662980697364,"name":"POST --- /api/auth","stop":1662980697389}],"attachments":[],"parameters":[],"start":1662980697362,"name":"tokenJWT","stop":1662980697389}],"attachments":[],"parameters":[],"start":1662980697295,"name":"\"before each\" hook","stop":1662980697389}],"attachments":[],"parameters":[],"labels":[{"name":"suite","value":"Teste de exclus√£o"}],"links":[],"start":1662980697294,"name":"[DELETE]-Excluir uma postagem","fullName":"[DELETE]-Excluir uma postagem","stop":1662980697389}